### PR TITLE
Sass::Plugin::Rack dwell time

### PR DESCRIPTION
**Pull request by AE9RB**
I ran into a performance problem while making https://github.com/dturnbull/googlyscript

I'm shipping googlyscript with custom sass middleware, but the dwell option is well suited for sass core.

### CODE REVIEW

**Comment by nex3** [comment]
This seems reasonable; I'll merge it in when I get home.

I do think a better solution here would be to only insert the middleware in the first place in development mode, but a performant default for when people don't do that is a good idea.

**Comment by AE9RB** [comment]
The performance hit is during development.  Google Closure has unique needs.  I'm not deploying Plugin::Rack.  Just a single small .sass file can add 10% to the page load time and a commercial project was slowing down about 300%.  Adding several seconds to every page load during javascript development is really quite painful.  The googlyscript server is capable of 450 request/second on my laptop with a single mongrel and I'm continuing to look for ways to improve that.

**Comment by nex3** [comment]
Oh, I see, the issue was that the large number of imported JS files were each causing an update check? That does sound unpleasant.

**Comment by AE9RB** [comment]
Thanks for adding this.  I'm well over 1000 requests/sec and the browser can't eat any faster so mission accomplished.

**Pull request merged**
