### PR TITLE
Fix for #1033

### PR DESCRIPTION
**Pull request by glebm**
Fixes latest Compass + Rails loading problem described in #1033.

### CODE REVIEW

**Comment by ServusJon** [comment]
It works beautiful!

**Comment by nex3** [comment]
How far back in terms of Rails versions does this work? I believe currently Sass works back to 2.3, and I'd like to preserve that compatibility if at all possible.

**Comment by glebm** [comment]
I think Railties are only available on Rails 3.0+. Rails 2.3 had reached end of life on June 25, 2013.

**Comment by glebm** [comment]
Updated with Rails 2 support. Please note that I have not tested Rails 2 compatibility, hopefully the test suite covers it.

**Pull request closed without merging**
