### PR TITLE
Fix doc: @extend is a directive, not selector

### PR DESCRIPTION
**Pull request by hlb**

### CODE REVIEW

**Comment by chriseppstein** [comment]
Maybe I'm too close to the problem, but "after the directive" could be misinterpreted as `@extend !optional .foo;` or `@extend .foo; !optional`.

Maybe a better phrasing would be "after the selector portion of the directive"?

**Comment by hlb** [comment]
maybe just "the end of the line"?

**Comment by chriseppstein** [comment]
It's only the end of the line in .sass files.

**Comment by hlb** [comment]
"in the end of directive"?

**Comment by robwierzbowski** [comment]
I believe the current wording is correct. After the **selector** part (`.this`, `%that`) of the **directive** statement.

**Comment by hlb** [comment]
ok :)

**Pull request closed without merging**
