### PR TITLE
Minitest5

### PR DESCRIPTION
**Pull request by movitto**
Greetings, we're looking to fix some packages in Fedora the were broken by a recent update to minitest (now at 5.3.1).

sass was one of the gems that was broken due to it's dependency on the old API.

http://koji.fedoraproject.org/koji/packageinfo?packageID=12284

I went through and patched the source to work against the new API and am sending a PR for hopeful inclusion upstream.

Thank you for your time.

### CODE REVIEW

**Comment by movitto** [comment]
Build after patch applied:

http://koji.fedoraproject.org/koji/taskinfo?taskID=7041045

**Comment by nex3** [comment]
What's minitest and why would we use it versus the built-in `Test::Unit`?

**Comment by lolmaus** [comment]
Minitest is the new Test:Unit.
- http://ruby-doc.org/stdlib-2.1.2/libdoc/minitest/rdoc/index.html
- http://ruby-doc.org/stdlib-2.1.2/libdoc/test/unit/rdoc/index.html

**Comment by movitto** [comment]
@lolmaus +1

@nex3 In recent releases of Ruby Test::Unit has been deprecated in favour of minitest

**Comment by nex3** [comment]
All right, if you get the Travis build passing I'll merge this in.

**Comment by movitto** [comment]
@nex3, hey srry for belated response. Had missed a few instances where the old API was used. Travis is now green.

**Pull request merged**
