### PR TITLE
Feature detection

### PR DESCRIPTION
**Pull request by chriseppstein**
Implementation for #766.

You can now call sass-supports($feature) in Sass files to check if Sass supports
some feature by name. This only returns true for the one major feature
added in the upcoming release so far: `sourcemaps`.

### CODE REVIEW

**Comment by nex3** [comment]
Done reviewing.

**Comment by chriseppstein** [comment]
@nex3 One reason why we might want to return true for features that we implement in 3.3 even though `sass-supports` is a new feature is that it would give other Sass implementations the ability to ship syntactic compatibility with 3.3 without needing to delay the release while they implement the other features. E.g. libsass or sassc might return false for `sourcemaps` while we return true.

/cc @akhleung @hcatlin

**Comment by HamptonMakes** [comment]
This feature would be extremely helpful for libsass/sassc! Though, just for clever naming, I like `can-do`

**Comment by chriseppstein** [comment]
@nex3 I'm done addressing your comments to-date on this PR.

**Comment by nex3** [comment]
Done responding.

**Comment by chriseppstein** [comment]
@nex3 I've addressed all remaining comments. Good to merge?

**Comment by nex3** [comment]
I think you missed [this comment](https://github.com/nex3/sass/commit/3f4b81a1305f7ec226335fb9f9245667b7514257#test-sass-functions_test-rb-P5). Other than that, go ahead.

**Pull request merged**
