### PR TITLE
Set the nth element in a list

### PR DESCRIPTION
**Pull request by chriseppstein**
Addresses #852.

### CODE REVIEW

**Comment by xzyfer** [comment]
:+1: I'm working no a very list intensive project at the moment where I've had to create a handful of list manipulation functions. This would be a lifesaver.

**Comment by chriseppstein** [comment]
@nex3 Ping.

**Comment by pdaoust** [comment]
For those who are waiting for this pull request to be merged and distributed to the masses, there are a lot of stopgap solutions in issue #852 that this pull request addresses.

**Comment by nex3** [comment]
A couple suggestions, otherwise :+1:.

**Comment by chriseppstein** [comment]
rebased on master and merged.

**Pull request closed without merging**
