### PR TITLE
Attempt to Fix all warnings from Sass.

### PR DESCRIPTION
**Pull request by vipulnsward**
Hi all, This is an attempt to fix different kinds of warnings form 
- Circular dependency loading
- Un- initialized variable.
- Use of File.exists? instead of File.exist?
- Parenthesis around ambiguous arguments, etc.

Not sure what the policy is about this. Just an attempt to clear out some warnings I see on Sinatra builds. (https://travis-ci.org/sinatra/sinatra/jobs/19503469)

### CODE REVIEW

**Comment by nex3** [comment]
We're not interested in avoiding warnings caused by uninitialized instance variables. We consider instance variables defaulting to `nil` to be a feature of Ruby, and use it accordingly.

If you remove the instance-variable changes, I'll merge this.

**Comment by vipulnsward** [comment]
Actually it just returns nil value, doesn't default to setting/initializing it.
https://github.com/ruby/ruby/commit/b996367eb50402cfb343e671a2ea2cf1450a8ec4

Do you wan't to me to remove the initializations to nil, with such a behaviour from Ruby?
Let me know, I'l update the PR.

**Comment by nex3** [comment]
Yes, please do remove the `nil` initializations.

**Comment by vipulnsward** [comment]
I see that all changes are already in master.

**Pull request closed without merging**
