### PR TITLE
Speed up Travis tests

### PR DESCRIPTION
**Pull request by junaruga**
Applied the case 5 of #2293. This fixes the ticket.
* Reduced 3 VMs (the idea 2)
* Unified VMs by different UNIX environment variable to 1 VM (the idea 1)
* Run "rake test:spec" just once for each Rubies.

We can expect the Travis total running time ("Ran for") to change from about 10 minutes to 3:50 minutes by this PR. (75% reduced!)

### CODE REVIEW

**Comment by nex3** [comment]
Can we make `extra/rake_with_matrix.rb` part of the Rakefile? That's where other tasks like it go.

**Comment by junaruga** [comment]
Yes! That's a great idea.
Let me try it.

**Comment by junaruga** [comment]
@nex3 I added 1 more commit to make the matrix part in `Rakefile`.

I deleted the logic to control `rubocop` task by `RUBOCOP` environment variable.
Because I wanted to avoid the rubocop rake task to be pre-defined by the environment variable. I want to control it from the matrix test task, referring this `Rakefile`: https://github.com/colszowka/simplecov/blob/master/Rakefile
But surprisingly, Rubocop works for every Ruby including Ruby < 2.2.0 now.
Rubocop supports Ruby 2.0.0 too.
https://github.com/bbatsov/rubocop/blob/master/.travis.yml
So, I changed the warning message too.

Also I unified the matrix test with `test`, because it looks simple.

I left 2 commits to compare easily.
If you like my modification, I can squash my 2 commits to 1 commit by myself.
Or you can squash it by yourself, when merging my commits.

**Comment by nex3** [comment]
This is looking good, but I'm worried that it's difficult to visually distinguish the various tests that are being run. Can you have it print a big header before each section? Something like

```
##################################################
################### Running tests ################
##################################################
```

**Comment by junaruga** [comment]
OK, I updated like this!

```
################################################################################
############### Running task: test:ruby, env: {"MATHN"=>"true"} ################
################################################################################
```

**Comment by nex3** [comment]
Looks great, thanks for all your hard work!

**Pull request merged**
