### PR TITLE
String functions

### PR DESCRIPTION
**Pull request by chriseppstein**
This pull adds some string functions that I feel are a fairly complete, but basic set of string manipulation functions.
1. `str-length` - the length of a string
2. `str-index` - the first index of a substring in another string
3. `str-insert` - inserts a string into another string.
4. `str-extract` - extract a substring from a string.
5. `to-upper-case` - convert a string to uppercase.
6. `to-lower-case` - convert a string to lowercase.

All of them are documented and tested. Feedback on the api, etc is welcome. Did I miss any very important string functions?

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Can you give a quick example of these in use? Curious how the syntax works.

**Comment by StanAngeloff** [comment]
I **sooo** needed this a couple of days ago and ended up doing magic with `@-function`s and `@-mixin`s. Other than the abbreviated prefix (`str` over `string`) and personal preferences about naming, I am very pleased with the API. Any methods missing, e.g., `str-append` or `str-prepend` can be added in code with no pain.

I'd also like to see `list-join` which may be out of the scope of this pull? I find myself concatenating lists very often, although a `@-function` is trivial to implement.

**EDIT**: come to think of it, list functions would be quite cool. `list-index-of`, `list-push`, `list-unique` come to mind. I may open up a separate issue, don't want to hijack the conversation in here.

**EDIT 2**: `index(..)` already exists in Sass.

**Comment by chriseppstein** [comment]
@micahgodbolt the tests are a good overview. did you read those yet?

**Comment by micahgodbolt** [comment]
Oh hey...those are links. Guess I should fully explore the page before asking questions. Those should work just fine. Thanks @chriseppstein

**Comment by chriseppstein** [comment]
@StanAngeloff I am planning on making a separate pull for lists soon. we already have `join` for lists.

**Comment by StanAngeloff** [comment]
@chriseppstein: Sounds very promising. RE `join`: joins two lists together, I should probably have used `implode` as in join a list and return a string, e.g. `implode('.', join((hello), (world), space)) -> 'hello.world'`.

I keep a handy `_functions.scss` around, hopefully lists (and other string extras) can be implemented as pure Sass `@-function`s. Is that the preferred approach when logic allows it?

**Comment by chriseppstein** [comment]
> Is that the preferred approach when logic allows it?

@StanAngeloff I'm on the fence about that and am curious how your experience has been. we should chat about that in a separate thread.

**Comment by chriseppstein** [comment]
We put this off because 3.2 was going to ship soon. @nex3, let's ship or merge this.

**Comment by chriseppstein** [comment]
@nex3 I will add a CHANGELOG entry for 3.3 for this. Any further comment before it lands on master?

**Comment by nex3** [comment]
Beginning code review now.

**Comment by nex3** [comment]
All of these functions should have `@param` documentation for all the parameters, at least to specify the types and also to specify whatever other constraints/non-obvious semantics exist.

**Comment by nex3** [comment]
Code review done.

**Comment by chriseppstein** [comment]
My response to the code review is complete. If I didn't comment on a particular comment, it means I acknowledge it and will address it as suggested.

**Comment by nex3** [comment]
I'll merge this in once you address the minor comments.

**Comment by industral** [comment]
could you plz merge it, I need that functionality :) @chriseppstein thanks for good work!

**Comment by domenic** [comment]
Argh I need this too.

**Comment by jkmaxwell** [comment]
@chriseppstein any chance to address the comments (especially the deletion of what looks like some critical code in the case switching) so this can get merged?

(also thanks, this is great!)

**Comment by ghost** [comment]
Whats the latest on this? Soon to be merged? So need this one :)
kinda annoying to know this is all neatly done just hanging in the air atm

**Comment by adamcoulombe** [comment]
Need this to create keyframe template mixins. Need this merged!!

**Comment by seafoox** [comment]
+1, would be very useful. Thx

**Comment by jkmaxwell** [comment]
@chriseppstein please address comments

**Comment by brentd** [comment]
@chriseppstein Would be great to see this merged. How can I help? Happy to take on the needed code changes.

**Comment by chriseppstein** [comment]
All feedback has been addressed and the string functions have been merged to master.

**Comment by baseten** [comment]
In SASS 3.3.0.alpha.149 these string functions are present, but str-extract refuses to work, it doesn't throw an error but simply outputs the function call as a string. I've tried the latest alpha (3.3.0.alpha.255 at time of writing) and this still happens.

**Comment by baseten** [comment]
Appears to have been renamed str-slice...

**Comment by Anahkiasen** [comment]
Is there an `str-replace` function or something similar ?

**Comment by vinayraghu** [comment]
`str-extract` is not working for me when I use SassMeister, which has `3.3.0.rc.1`
https://gist.github.com/rvinay88/7553853

**Comment by nex3** [comment]
@Anahkiasen: not currently.

@rvinay88: it was renamed to `str-slice`.

**Pull request closed without merging**
