### PR TITLE
Added @path annontation to perform path mapping.

### PR DESCRIPTION
**Pull request by emphaticsunshine**
See: #1094, #451
- Made changes in perform.rb to visit path directives
  to map files.
- Made changes in import.rb to replace the mapped file.

### CODE REVIEW

**Comment by emphaticsunshine** [comment]
See the following gist for implementation.
https://gist.github.com/emphaticsunshine/10959128

**Comment by emphaticsunshine** [comment]
@nex3 or @chriseppstein can you please give it a look? This is very important feature for the company I work for. This feature enables us to do some A/B testing in sensible manner.

**Comment by nex3** [comment]
In general when adding a new feature, it's a good idea to communicate us to make sure the feature is one we want and that we approve of its design. Otherwise you can end up spending effort writing code that will go unused.

In this case, it's difficult to tell exactly what the feature is doing, since there's no documentation in the patch, but I'm pretty sure it's not something we're interested in supporting. It has weird global effects, it subverts the importer system, and in general adding load paths from within a stylesheet isn't a good practice.

**Comment by drewwells** [comment]
@nex3 rather than abruptly closing this PR, please describe "weird global effects" and other concerns you have.  The paths feature is explicitly requested in import_v2 wishlist and something that the community finds value in, but you seem to disagree here.  Paths is a basic feature and critical to how other static file tools use ie. RequireJS.

If you can describe your thoughts on this matter, we can find a solution to implementing this feature.

#1094 

### Paths

A way to setup shortcut paths (like Require.js)

// No syntax intended, only the purpose

```
@paths (
    "bootstrap": "../components/bootstrap-sass/vendor/assets/stylesheets/bootstrap"
);

@import "bootstrap";
```

**Comment by nex3** [comment]
> If you can describe your thoughts on this matter, we can find a solution to implementing this feature.

I dislike including configuration in source files in general for a number of reasons. It violates separation of concerns by mixing configuration with styling, it hurts reusability by encoding the author's preferences indelibly in the unit of reuse, it adds a considerable amount of complexity to the language that would otherwise be isolated in the external configuration, and it requires that global options be specified locally to a single stylesheet.

I dislike encoding load paths in source files in particular because paths are usually system-specific, so it adds a surface where it's easy to make a stylesheet brittle and nonportable. In addition, the behavior isn't well-defined in terms of Sass's `Importer` abstraction; every load path is encoded as a separate `Importer` object, and these objects may not necessarily correspond to the filesystem. There's not a simple mapping between strings and `Importer`s, so it's not clear how this would work with non-filesystem importers.

**Comment by chriseppstein** [comment]
I don't understand why Sass's existing importer abstraction and load path mechanism is not sufficient for the use case.

RE abruptly closing this PR, the [contribution guidelines](http://sass-lang.com/community#Contribute) are very clear:

> New feature requests should be made on the issue tracker and discussed with the core team before implementation begins to avoid wasted effort.

Once a feature has been vetted and agreed to as a proposal, then we're happy to entertain patches that implement that feature.

**Comment by nex3** [comment]
> I don't understand why Sass's existing importer abstraction and load path mechanism is not sufficient for the use case.

Currently the language itself (as opposed to the command-line interface or the `Sass::Engine` API) is entirely importer-agnostic. I think that's a good property that's worth preserving, but it means that we can't just always instantiate a FilesystemImporter when someone says "add this string as a load path". I think the place for that sort of thing is external to the language, likely in the configuration file proposed in #1155.

**Comment by chriseppstein** [comment]
@nex3 My comment was directed to @drewwells and @emphaticsunshine. I don't understand why the features in Sass 3.3 are not sufficient for them.

**Comment by drewwells** [comment]
@chriseppstein, what feature?

> Imports may contain #{} interpolation, but only with certain restrictions. It’s not possible to dynamically import a Sass file based on a variable; interpolation is only for CSS imports. As such, it only works with url() imports. For example:

Issues have been filed #1218 , but marked as duplicate #739, a ticket with no obvious objective.

**Comment by chriseppstein** [comment]
@drewwells In that ticket, @nex3 explained that you can define a mixin that implements the branching logic that you need.

#739 is a generic proposal to allow interpolation within and conditionals around @import statements.

**Comment by drewwells** [comment]
You're saying we should put our entire codebase in mixins?  If I told my
team that is the solution offered by SASS, they would throw me in the mad
house.

**Comment by chriseppstein** [comment]
Only the parts that have to vary for your test. Other solutions also exist. For instance, you could define the features using placeholder selectors and only extend them with concrete classes when you know you're going to need them.

**Comment by drewwells** [comment]
I agree those are good one off solutions but we do a lot of development within tests.  We also expect to write code that can easily be folded into the main once complete.  Mixins and placeholders aren't practical for entire page redesigns.

**Comment by drewwells** [comment]
If we could put sass files inside control directives that would be much easier.  Although paths would offer better options for the organization of our code.

**Pull request closed without merging**
