### PR TITLE
Back port: Speed up Travis tests

### PR DESCRIPTION
**Pull request by junaruga**
This is a cherry-pick and back port to stable branch from next branch: 7ad03a953442619aa37dcc48283ceb16ca31e92f .

This PR is from below discussion.
https://github.com/sass/sass/pull/2306#issuecomment-306887738

### CODE REVIEW

**Comment by nschonni** [comment]
I'm not sure if the 1.8.x and 1.9.x ones should stay since they are passing on the current stable.
:100: on removing the JRuby and `rbx` since they've been failing forever

**Comment by junaruga** [comment]
@nschonni 

> I'm not sure if the 1.8.x and 1.9.x ones should stay since they are passing on the current stable.

Yeah, that is my concern.
In the case of `next` branch, those were removed by commit: https://github.com/sass/sass/commit/bceb3e61b6e070669b47fbe935ebe90f85e286ff .

Will we remove those Rubies? or Remove only `1.9.2`?

```
- 1.8.7
- 1.9.2
- 1.9.3
```

As a information, Ruby < 2.2 has not been maintained officially.
https://www.ruby-lang.org/en/downloads/

**Comment by nex3** [comment]
We still need to support 1.8 and 1.9 for stable, so we should continue testing them.

**Comment by junaruga** [comment]
Ok but why does Ruby 1.9 have 2 cases both 1.9.2 and 1.9.3?
Keeping 1.9.3 is good enough isn't it?

**Comment by nex3** [comment]
Yeah, just 1.9.3 should be fine.

**Comment by junaruga** [comment]
OK! I rebased with keeping Ruby 1.8 and 1.9.

**Comment by nex3** [comment]
Thanks!

**Pull request merged**
