### PR TITLE
Named arguments

### PR DESCRIPTION
**Pull request by chriseppstein**
This branch adds named argument calling conventions to mixins and functions.

### CODE REVIEW

**Comment by nex3** [comment]
I've started working on some modifications on my keyword-args branch. They aren't finished yet, though.

**Comment by bcoughlan** [comment]
Did this feature ever make it in?

**Comment by nex3** [comment]
Yes. It's been in there since 3.1.0.

**Comment by bcoughlan** [comment]
Apologies, just saw it in the docs.

**Pull request merged**
