### PR TITLE
Minor Update in Contributing - make the url clickable

### PR DESCRIPTION
**Pull request by adelatorrefoss**
I noticed that a url not clickable is very unconfortable. I hope this small change helps.

### CODE REVIEW

**Comment by nex3** [comment]
This file is plain text, not markdown. There's no way to make a link in it clickable in GitHub's interface.

**Comment by lolmaus** [comment]
Why not rename it to `CONTRIBUTING.md`?

**Comment by nex3** [comment]
I'd accept a pull request that did that.

**Comment by adelatorrefoss** [comment]
Thanks! Ill do that asap. :-)

**Pull request closed without merging**
