### PR TITLE
Support compass watching

### PR DESCRIPTION
**Pull request by chriseppstein**
These are the changes I needed to make in order to remove Compass's compiler/watcher and replace it with a simple adapter to the Sass compiler/watcher.

None of the watching code in Sass is tested at all and these changes are relatively simple, but if you think some of it needs testing, I can add tests.

### CODE REVIEW

**Comment by nex3** [comment]
Done reviewing. Please also add changelog entries for the user-visible changes here. Tests would be nice, but don't feel obligated to block the PR on them.

**Comment by chriseppstein** [comment]
I added changelog entries. I'd like to add a `--clean` option to sass but I will do that as a separate PR.

**Comment by chriseppstein** [comment]
@nex3 :+1: ?

**Comment by nex3** [comment]
:thumbsup:

**Pull request merged**
