### PR TITLE
Use literate programming for JS API specs

### PR DESCRIPTION
**Pull request by nex3**

### CODE REVIEW

**Review by jathak — APPROVED** [review]
Is the plan to do something similar for the user-facing documentation in js-api-doc, or is that not feasible since we need the actual documentation to be in comments so it's accessible to TypeDoc?

**Comment by nex3** [comment]
My plan is to leave js-api-doc as-is, for the reason you describe. It also follows a much more typical pattern of "documenting specific types" rather than the spec-style pattern of "specifying behavior which is sometimes but not always attached to types".

**Comment by jgerigmeyer** [comment]
@nex3 I think this PR (specifically the removal of `spec/js-api/index.d.ts`) is breaking CI currently on dart-sass and sass-spec repos:

- https://github.com/sass/sass-spec/actions/runs/4824362331
- https://github.com/sass/dart-sass/actions/runs/4824310028

**Comment by nex3** [comment]
Oops, forgot to land corresponding updates elsewhere. I bet it's also breaking sass-site.

**Comment by nex3** [comment]
@jgerigmeyer Should be fixed now, let me know if it's not.

**Comment by jgerigmeyer** [comment]
@nex3 That worked -- thanks!

**Pull request merged**
