### PR TITLE
If function

### PR DESCRIPTION
**Pull request by chriseppstein**
This branch adds an if(bool, when_true, when_false) function.

### CODE REVIEW

**Comment by chriseppstein** [comment]
I've been using this in compass for a couple weeks now and it's incredibly useful. I've made a couple tweaks to it, for instance, the false value is optional now.

**Comment by ChristianPeters** [comment]
This function deserves its place in the reference. I needed a ternary operator and remembered that I have read something similar somewhere on github some time ago. It took me quite a while to find this pull request...

**Comment by kflorence** [comment]
This doesn't seem to work for variable assignment:

``` sass
$some-variable: if ( true, true, false ); // => "if true, true, false"
```

**Comment by chriseppstein** [comment]
@kflorence you can't put a space after `if`

**Comment by kflorence** [comment]
Yep, that's the problem. Silly.

**Pull request merged**
