### PR TITLE
added 'rebeccapurple' to named colours

### PR DESCRIPTION
**Pull request by pdaoust**
[In memory of Rebecca Meyer](http://www.zeldman.com/2014/06/10/the-color-purple/), the colour [`rebeccapurple` has been added](http://dev.w3.org/csswg/css-color/#valuedef-rebeccapurple) to the CSS4 Colour Module.

### CODE REVIEW

**Comment by maxw3st** [comment]
A much diserved tribute to a family that has contributed much to the growth
of the WWW and suffered multiple and tragic losses recently.

On Tue, Jun 24, 2014 at 12:03 PM, pdaoust notifications@github.com wrote:

> In memory of Rebecca Meyer
> http://www.zeldman.com/2014/06/10/the-color-purple/, the colour
> rebeccapurple has been added
> http://dev.w3.org/csswg/css-color/#valuedef-rebeccapurple to the CSS4
> 
> ## Colour Module.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/pdaoust/sass stable
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/sass/sass/pull/1298
> Commit Summary
> - added 'rebeccapurple' to named colours
>   http://dev.w3.org/csswg/css-color/#valuedef-rebeccapurple
> 
> File Changes
> - _M_ lib/sass/script/value/color.rb
>   https://github.com/sass/sass/pull/1298/files#diff-0 (1)
> 
> Patch Links:
> - https://github.com/sass/sass/pull/1298.patch
> - https://github.com/sass/sass/pull/1298.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sass/sass/pull/1298.

## 

Max West

**Comment by lolmaus** [comment]
What is the status of this color name support in browsers?

**Comment by pdaoust** [comment]
@lolmaus I've heard browsers are already promising to support it, or have already implemented it in their development branches. Two notes: I couldn't find anything for Opera, and IE only has a 'we're looking into it' promise.

https://code.google.com/p/chromium/issues/detail?id=384254
https://bugzilla.mozilla.org/show_bug.cgi?id=1024642
https://bugs.webkit.org/show_bug.cgi?id=133804
https://connect.microsoft.com/IE/feedback/details/895019/support-beccapurple-as-html-named-color

**Comment by Snugug** [comment]
Opera uses Chromium, so when it lands in Chromium it'll land in Opera.

**Comment by pdaoust** [comment]
@Snugug duh, of course -- totally forgot that Opera had dropped their own engine. Thanks for the reminder :)

**Comment by nex3** [comment]
Closed by e5c7b8707eff049ef12ea0d2a579e008af9ce00c.

**Pull request closed without merging**
