### PR TITLE
Add `nil` literal

### PR DESCRIPTION
**Pull request by petebrowne**
Here's a common use use case for a `nil` literal:

``` scss
@mixin block-colors($background-color, $border-color: nil) {
  $border-color: darken($background-color, 10%) !default;

  background-color: $background-color;
  border-color: $border-color;
}
```

This is semantically different than using `false` in conjunction with an `@if` directive. Plus, guarded assignment can be used to set a dynamic default value.

### CODE REVIEW

**Comment by nex3** [comment]
I think this is a good thing to add, but I think "null" is a better name for this. It's used by a wider variety of languages, including in particular Javascript.

I'll add more comments on the patch.

**Comment by petebrowne** [comment]
I agree with the name change - I'll work on incorporating the changes you're suggesting. Thanks

**Comment by Anahkiasen** [comment]
I agree with the idea that null == 0 (but null !== 0), seems simpler and more logical to me.

**Comment by petebrowne** [comment]
What do you think @nex3 @chriseppstein? Should `1 + null` return `1` or raise a SyntaxError?

**Comment by chriseppstein** [comment]
Syntax error. We can relax it later if we feel it's wrong, but changing to syntax error later is very hard.

**Comment by nex3** [comment]
I'm not at all fond of Javascript's aggressive type coercion. `1 + null` should be an error, and `null != 0`.

**Comment by petebrowne** [comment]
I've opened a separate pull request, #374, with the suggested changes.

**Pull request closed without merging**
