### PR TITLE
Add grey to the list of Sass Script colors

### PR DESCRIPTION
**Pull request by robwierzbowski**
Addresses #738.

### CODE REVIEW

**Comment by robwierzbowski** [comment]
Not sure why grey is overriding gray in the tests.

**Comment by robwierzbowski** [comment]
`grayscale()` returns the 'grey' version of every gray color (e.g., lightgrey, dimgrey, etc.). Changed the test to go along with that pattern.

**Comment by nex3** [comment]
Are there any other specced color names we don't support?

**Comment by robwierzbowski** [comment]
The list to check is probably http://en.wikipedia.org/wiki/Web_colors#X11_color_names. I can go through them sometime this weekend.

**Comment by nex3** [comment]
Thanks. I'll wait on merging this until you do so.

**Comment by robwierzbowski** [comment]
From what I see everything is accounted for. The only supported alternate spellings I found are grey/gray.

**Comment by nex3** [comment]
This was merged as 54ea0d46c493972a462a8e1c59e8e5db7be4715d.

**Pull request closed without merging**
