### PR TITLE
Upgrade listen

### PR DESCRIPTION
**Pull request by chriseppstein**
This upgrades the watcher to use listen 1.1.x and has a substantial rewrite of the watcher code.

### CODE REVIEW

**Comment by nex3** [comment]
Done reviewing.

**Comment by chriseppstein** [comment]
@nex3 I've addressed your code review comments. I've also refactored the watching code further to delegate watched directories and files to the importer objects and I've added tests for the watcher.

**Comment by nex3** [comment]
Other than a couple small comments, I'm happy with where this is up through 5f47ae305a4f110a8ecb6f728e09b3ff0be86be8. As I mentioned in 1fa0c477bca21307e09267535ef53bb6a2a3bf55, I feel like half the commit should be a separate pull request and the other half should be integration tests rather than unit tests.

Writing integration tests involving file watching is really gross, though, so if you don't want to do that I'm fine with just rebasing and merging up through 5f47ae305a4f110a8ecb6f728e09b3ff0be86be8.

**Comment by chriseppstein** [comment]
Integration tests are good, let's create an issue to track making them and address that if we find an instance where the current testing approach is not good enough -- at least we have some tests now ^_^

**Comment by nex3** [comment]
Done reviewing 1fa0c477bca21307e09267535ef53bb6a2a3bf55.

**Pull request merged**
