### PR TITLE
add first class mixins to embedded sass protobuf and JS API

### PR DESCRIPTION
**Pull request by connorskees**
See https://github.com/sass/sass/pull/3626 and https://github.com/sass/dart-sass/pull/2073/

### CODE REVIEW

**Review by nex3 — APPROVED** [review]

**Comment by ntkme** [comment]
We should bump the version number in https://github.com/sass/sass/blob/main/spec/EMBEDDED_PROTOCOL_VERSION

**Comment by stof** [comment]
As this creates a new kind of value that can be sent to the host, is it actually a minor version or a major one ?

**Comment by ntkme** [comment]
Historically this kind of change has been considered as minor. The host can upgrade to new protocol version without supporting added type, and all previous feature would still work.

**Review by nex3 — APPROVED** [review]

**Comment by ntkme** [comment]
This looks good! Only thing is that we should probably edit the title of this PR as the scope of this PR has increased.

**Review by nex3 — APPROVED** [review]

**Pull request merged**
