### PR TITLE
Changes most references of Fixnum class to Integer, to account for deprecation of Fixnum and Bignum classes in Ruby 2.4.0

### LINKED ISSUE #2218: "Fixnum is deprecated" // warning while converting scss to css
**I tried to create a flex based css when I encountered this message:**

```
$ sass bootstrap-flex.scss bootstrap-flex.css
/usr/local/lib/ruby/gems/2.4.0/gems/sass-3.4.23/lib/sass/util.rb:1109: warning: constant ::Fixnum is deprecated
```

## Setup

bootstrap-4.0.0-alpha.5

**Sass version:**
`Sass 3.4.23 (Selective Steve)`

**Ruby version:**
`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`

### PR DESCRIPTION
**Pull request by richiethomas**
Closes #2218

### CODE REVIEW

**Comment by nex3** [comment]
Thanks!

**Comment by AnatolyRugalev** [comment]
@nex3 

Can you please tell when this changes will be released? Arch Linux package is broken because of this deprecation warning. Thank you!

**Comment by nex3** [comment]
I just got back from a two-month leave, and I'm currently making my way through the backlog of issues and pull requests. Once I finish that, I'll cut a release.

**Comment by AnatolyRugalev** [comment]
@nex3 alright, thanks!

**Pull request merged**
