### PR TITLE
Add appveyor.yml config to run tests on Appveyor Windows CI service

### PR DESCRIPTION
**Pull request by mprins**
Add Appveyor configuration file so this can be built on the Appveyor CI service (windows).

This basically runs the same script as Travis-CI does using `rake`

To get this going on the sass repo one of the project owners needs to:
- login at https://ci.appveyor.com/signup/free using your Github account
- use the "+ new project" on top of the page to select and add the Compass project
- merge this PR

BTW this service is free for opensource projects (http://www.appveyor.com/pricing)

### CODE REVIEW

**Comment by mprins** [comment]
see also Compass/compass#1783

**Comment by nex3** [comment]
This is very cool, but I'm a little confused—the Appveyor site says that it's for .NET stuff and doesn't make any mention of Ruby. How do Ruby/RubyGems/Bundler et al. get installed?

**Comment by mprins** [comment]
The VM's have Ruby 1.9.3p545 (2014-02-24) [i386-mingw32] and Bundler 1.7.o installed so running `bundle install` and then `rake` pretty much take care of running the tests. Ofcourse the choice of runtimes in not as extensive as on Travis but it's a start...

This is what it looks like: https://ci.appveyor.com/project/mprins/sass

Also see: http://www.appveyor.com/docs/installed-software and http://help.appveyor.com/discussions/problems/691-ruby-gem-install-bundler-hanging and the [Compass PR 1783](Compass/compass#1783) for setting this up, basically login with GH account and add the project.

**Comment by nex3** [comment]
Wow, there are a lot of failing Windows tests right now. I'd like to get those fixed before turning this on for the main repo.

**Comment by mprins** [comment]
okidokie; I just updated this to take advantage of the extra Ruby versions that were recently installed.

**Comment by mprins** [comment]
also this: http://github-multi-status.herokuapp.com/ will enable seeing the build status of both Travis and AppVeyor on pull requests.

**Comment by cvrebert** [comment]
No need for that Heroku app anymore: https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

**Comment by chriseppstein** [comment]
Given the large number of visitors to the sass website from windows (more than 50%) I'd like to land this soon.

**Comment by nex3** [comment]
Do we have any way to actually debug and fix tests on Windows?

**Comment by mprins** [comment]
closing since this was opened >2yrs ago and has not landed and by now is way out-of-date anyway

**Pull request closed without merging**
