### PR TITLE
Don't pet that kitty. Make a donation.

### PR DESCRIPTION
**Pull request by chriseppstein**
The kitty petting thing is creepy. I've removed it and made a more socially responsible recommendation instead (to donate to a non-profit). I also updated my info while I was in there.

### CODE REVIEW

**Comment by jina** [comment]
all looks good to me!

**Comment by HamptonMakes** [comment]
How about make a donation to us. ;)

**Comment by chriseppstein** [comment]
@hcatlin When we can take donations online, let's add that.

**Comment by davidkpiano** [comment]
I'd make a note that Eyeglass is for Node-Sass. Might cause confusion, as this is the Ruby Sass repo.

**Comment by nex3** [comment]
:+1:

**Pull request merged**
